name = "github-stars-manager"
main = "src/index.ts"
compatibility_date = "2026-08-20"

[assets]
directory = "../dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "github-stars-manager"
database_id = "fd7e943c-2420-4a87-b78e-802bb68be539"

# Configure AUTH_TOKEN with `wrangler secret put AUTH_TOKEN` when needed.
